package model;

import java.util.Date;

// Generated 2013-12-9 16:05:09 by Hibernate Tools 3.4.0.CR1

/**
 * TpfDownloadrecord generated by hbm2java
 */
public class Downloadrecord implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3453333187303793454L;
	private Integer recordid;
	private Integer resourceid;
	private Integer userid;
	private Date downloadtime;

	public Downloadrecord() {
	}

	public Downloadrecord(Integer resourceid, Integer userid) {
		this.resourceid = resourceid;
		this.userid = userid;
	}

	public Integer getRecordid() {
		return this.recordid;
	}

	public void setRecordid(Integer recordid) {
		this.recordid = recordid;
	}

	public Integer getResourceid() {
		return this.resourceid;
	}

	public void setResourceid(Integer resourceid) {
		this.resourceid = resourceid;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}
	
	public Date getDownloadtime() {
		return this.downloadtime;
	}

	public void setDownloadtime(Date downloadtime) {
		this.downloadtime = downloadtime;
	}

}
