package model;

// Generated 2013-12-5 14:18:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TpfResource generated by hbm2java
 */
public class Resource {

	/**
	 * 
	 */
	private Integer resourceid;
	private String title;
	private String sdescribe;
	private Date createtime;
	private String link;
	private int authorid;
	private int ispass;
	private int downloadtimes;
	private String onlinelink;
	private String filename;
	private String respic;
	private String tag;
	private Integer viewtimes;
	private Double size;
	private String restype;
	private int ispublic;
	private int coin;

	public Resource() {
	}

	public Resource(String sdescribe, Date createtime, String link,
			int authorid, int ispass, int downloadtimes, String filename,
			int ispublic, int coin) {
		this.sdescribe = sdescribe;
		this.createtime = createtime;
		this.link = link;
		this.authorid = authorid;
		this.ispass = ispass;
		this.downloadtimes = downloadtimes;
		this.filename = filename;
		this.ispublic = ispublic;
		this.coin = coin;
	}

	public Resource(String title, String sdescribe, Date createtime,
			String link, int authorid, int ispass, int downloadtimes,
			String onlinelink, String filename, String respic, String tag,
			Integer viewtimes, Double size, String restype, int ispublic,
			int coin) {
		this.title = title;
		this.sdescribe = sdescribe;
		this.createtime = createtime;
		this.link = link;
		this.authorid = authorid;
		this.ispass = ispass;
		this.downloadtimes = downloadtimes;
		this.onlinelink = onlinelink;
		this.filename = filename;
		this.respic = respic;
		this.tag = tag;
		this.viewtimes = viewtimes;
		this.size = size;
		this.restype = restype;
		this.ispublic = ispublic;
		this.coin = coin;
	}

	public Integer getResourceid() {
		return this.resourceid;
	}

	public void setResourceid(Integer resourceid) {
		this.resourceid = resourceid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSdescribe() {
		return this.sdescribe;
	}

	public void setSdescribe(String sdescribe) {
		this.sdescribe = sdescribe;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public int getAuthorid() {
		return this.authorid;
	}

	public void setAuthorid(int authorid) {
		this.authorid = authorid;
	}

	public int getIspass() {
		return this.ispass;
	}

	public void setIspass(int ispass) {
		this.ispass = ispass;
	}

	public int getDownloadtimes() {
		return this.downloadtimes;
	}

	public void setDownloadtimes(int downloadtimes) {
		this.downloadtimes = downloadtimes;
	}

	public String getOnlinelink() {
		return this.onlinelink;
	}

	public void setOnlinelink(String onlinelink) {
		this.onlinelink = onlinelink;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getRespic() {
		return this.respic;
	}

	public void setRespic(String respic) {
		this.respic = respic;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Integer getViewtimes() {
		return this.viewtimes;
	}

	public void setViewtimes(Integer viewtimes) {
		this.viewtimes = viewtimes;
	}

	public Double getSize() {
		return this.size;
	}

	public void setSize(Double size) {
		this.size = size;
	}

	public String getRestype() {
		return this.restype;
	}

	public void setRestype(String restype) {
		this.restype = restype;
	}

	public int getIspublic() {
		return this.ispublic;
	}

	public void setIspublic(int ispublic) {
		this.ispublic = ispublic;
	}

	public int getCoin() {
		return this.coin;
	}

	public void setCoin(int coin) {
		this.coin = coin;
	}

}
